---

language: rust
rust:
  - stable
cache: cargo

services:
  - docker

script:
  - cargo test --verbose
  - bash scripts/docker_build.sh

deploy:
  provider: script
  script: bash scripts/docker_push.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|develop)$
