[package]
name = "glass-pane"
version = "0.1.0"
authors = ["Laura Demkowicz-Duffy <laura@laurademkowiczduffy.co.uk>"]
edition = "2018"

[dependencies]
prometheus = "0.11.0"
tokio = "0.3.5"
rcon = "0.3.1"
structopt = "0.3.21"
env_logger = "0.8.2"
